### PR TITLE
[BUGFIX] Trying to fix mistyping which might be causes error in like-pattern e…

### PR DESCRIPTION
**Pull request by matveykortsev**
Trying to fix error in like-pattern expectations for ClickHouse which is described in this issue:
https://github.com/great-expectations/great_expectations/issues/8446

### CODE REVIEW

**Review by anthonyburdi — APPROVED** [review]
Thank you for finding this issue and for this bugfix!

**Comment by anthonyburdi** [comment]
@matveykortsev, thank you for this fix. Would you be able to sign the CLA with your email address [m.kortsev@prequelapp.com](mailto:m.kortsev@prequelapp.com)? Once that is done we can merge.

**Comment by matveykortsev** [comment]
@cla-bot check

**Comment by matveykortsev** [comment]
@anthonyburdi Done

**Pull request merged**
