### PR TITLE
[BUGFIX] Fix datadocs icons

### LINKED ISSUE #10475: No red or green status markers in data docs in Great Expectations
**Describe the bug**
After running any of my created checkpoints - I could not see `red` or `green` status markers in data docs in Great Expectations:
image

The same appears for my collegues and the same appears for older (run, for example 2-5 months ago) data-docs results.

**To Reproduce**
Run any Great Expectations checkpoint and build data-docs. 
```
checkpoint = context.add_or_update_checkpoint(
    name=f"{layer}_{datasource}_checkpoint",
    run_name_template=f"%Y%m%d-%H%M%S-{layer}-{datasource}",
    validations=[
        {
            "batch_request": b_request, # request variable title
            "expectation_suite_name": e_suite, # suite variable title
        },
    ],
    action_list=[
        {
            "name": "store_validation_result",
            "action": {"class_name": "StoreValidationResultAction"},
        },
        {"name": "update_data_docs", "action": {"class_name": "UpdateDataDocsAction"}},
    ],
)
context.add_or_update_checkpoint(checkpoint=checkpoint)
checkpoint_result = checkpoint.run()
context.build_data_docs()
context.open_data_docs()
```

**Expected behavior**
In data-docs rendered _html_, in the STATUS cells you can see `green` (if success: True) and `red` (if success: False).

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: tried on both 0.18.19 & 0.18.8
 - Data Source: Spark data frames from delta tables and csv files
 - Cloud environment: delta tables and csv files are being loaded from AWS S3

### PR DESCRIPTION
**Pull request by tyler-hoffman**
We were getting 403s on our old font awesome kit. Not sure why, and I don't have access to it. It's free and easy to make a new one, so I just did that originally, but then switched to a cdn. Is that preferable?

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `ruff format` + `ruff check`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

### CODE REVIEW

**Review by joshua-stauffer — APPROVED** [review]
👍

**Comment by jwalant-dattani** [comment]
Could this be applied in 0.18 version as well? Same issue on that version too.

**Comment by jwalant-dattani** [comment]
@tyler-hoffman Is it possible to apply this in version 0.18. I do see the comment in issue that older versions are not supported. However, workaround suggested there without upgrades seems cumbersome for this simple fix. If there is a link you can point me to, I can raise a PR. I checked the readme on contributing, but could not follow workflow to apply this on older version, given you've already fixed it in develop. Appreciate any pointers. Thanks.

**Comment by jwalant-dattani** [comment]
Thanks @tyler-hoffman

**Comment by tyler-hoffman** [comment]
No problem @jwalant-dattani ! FYI I believe we plan to publish the release for this later today.

We've formally dropped support for pre-v1, but this was a special case. LMK if you have any issues once it's published

**Comment by jwalant-dattani** [comment]
Thanks @tyler-hoffman. Verified, works on 0.18.22 as well now.

**Pull request merged**
