### PR TITLE
[DOCS] add in-memory add expectation suite 

### PR DESCRIPTION
**Pull request by tb102122**
update docuemntation code

- [X] Code is linted
- [X] Appropriate tests and docs have been updated

### CODE REVIEW

**Comment by tb102122** [comment]
related to https://github.com/great-expectations/great_expectations/issues/7888

**Comment by tb102122** [comment]
@anthonyburdi @kenwade4 Anything I should follow up? These test are not related to the files I have changed.

**Comment by kenwade4** [comment]
@tb102122 the only thing you modified was `tests/integration/docusaurus/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.py` correct? Everything else is just lint changes

**Review by kenwade4 — APPROVED** [review]

**Comment by tb102122** [comment]
@kenwade4 yes that is correct

**Comment by kenwade4** [comment]
The stages that are failing are doing so because `References secure file. PRs from repository forks are not allowed to access secrets in the pipeline`

I'll have someone internally force merge this if it doesn't go through here. Thanks for the fix.

**Pull request merged**
