### PR TITLE
[CONTRIB] Handle connection error during version check

### PR DESCRIPTION
**Pull request by stejin**
Solution for https://support.greatexpectations.io/hc/en-us/requests/196

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `ruff format` + `ruff check`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, visit our [community resources](https://docs.greatexpectations.io/docs/core/introduction/community_resources#contribute-code-or-documentation).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

### CODE REVIEW

**Review by joshua-stauffer — APPROVED** [review]
hey @stejin , this looks good - you'll need to sign the CLA to run the rest of the CI steps.

**Comment by stejin** [comment]
@cla-bot check

**Comment by stejin** [comment]
@joshua-stauffer - done.

**Comment by billdirks** [comment]
@stejin, We are having some permission issues for contributors at the moment that need to be resolved. Because of this, I've created [this PR](https://github.com/great-expectations/great_expectations/pull/10720) and cherry-picked your commits so you will be listed as an author. This will get your change into this weeks release.

**Comment by adeola-ak** [comment]
Thank you again for your patience. The duplicated issue has been merged. Closing due to this comment:
> @stejin, We are having some permission issues for contributors at the moment that need to be resolved. Because of this, I've created [this PR](https://github.com/great-expectations/great_expectations/pull/10720) and cherry-picked your commits so you will be listed as an author. This will get your change into this weeks release.

**Pull request closed without merging**
