### PR TITLE
[BUGFIX] fix class name 

### PR DESCRIPTION
**Pull request by tb102122**
Changes proposed in this pull request:

-  expectation not available in release and documentation

### Definition of Done

- [X] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [X] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [X] I have run any local integration tests and made sure that nothing is broken.

### CODE REVIEW

**Review by kenwade4 — APPROVED** [review]
Thanks for continuing to maintain your contribution @tb102122

**Comment by kenwade4** [comment]
@tb102122 Can you please [lint your code](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style/#linting) and merge in latest from develop?

**Comment by tb102122** [comment]
@kenwade4 Done

**Comment by anthonyburdi** [comment]
Force merged per @kenwade4 request.

**Pull request merged**
