### PR TITLE
[BUGFIX] Adding masking for azure connectionstrings

### PR DESCRIPTION
**Pull request by c624ad2**
- [x] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues) -> [Issue #7997](https://github.com/great-expectations/great_expectations/issues/7997)
- [x] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [x] Code is linted

    ```
    black .

    ruff . --fix
    ```
- [ ] Appropriate tests and docs have been updated

For more details, see our [Contribution Checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist), [Coding style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style), and [Documentation style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/docs_style).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

### CODE REVIEW

**Comment by c624ad2** [comment]
@cla-bot check

**Comment by Kilo59** [comment]
Thanks for doing this.
@c624ad2 could you provide a code block that causes the raw connection_string to be exposed?

**Comment by tyler-hoffman** [comment]
Hey @c624ad2 I wanted to double check something on this PR.

It looks like we appear to already have handling for azure connection strings in `mask_db_url`: https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/data_context/util.py#L192. Based on the exception you said was being raised, if I'm reading things correctly, it sounds like your connection string must not start with `DefaultEndpointsProtocol`. Is there any chance it's getting written into the config file incorrectly? The most likely thing that came to mind for me was that maybe it was getting an extra set of quotes or whitespace.

**Review by Kilo59 — CHANGES_REQUESTED** [review]
We need to be able to reproduce this bug before accepting a fix for it.

**Comment by c624ad2** [comment]
> 

I get the connection string from azure so it is on the right format (I also double checked it starts with `DefaultEndpointsProtocol`). I see the code you have linked to there and that should fix my issue yes! However I am using version `0.15.3` of `great_expectations` and it is not available there. Do you know if it already is available in a newer release or when it will be available?

This PR can probably just be closed now and then I'll just update my version of `great_expectations`!

**Comment by tyler-hoffman** [comment]
Hey @c624ad2 , it looks like this went out in release 0.15.49, per https://docs.greatexpectations.io/docs/changelog/ (it's #7139). I agree that it looks like this PR can be closed out. I'll mark the original issue as closed out as well. Thanks a ton for working with us on this!

**Pull request closed without merging**
