### PR TITLE
[BUGFIX]  added case insensitivity for expectations per issue#8619

### PR DESCRIPTION
**Pull request by slkasper**
## Description
Found a way to address issue #8619 when core expectations raise a KeyError exception whenever upper case column names are used in expectation calls.  I did not see where this would have changed at any point though.

- [x] Description of PR changes above includes a link to [an existing GitHub issue #8619 ](https://github.com/great-expectations/great_expectations/issues/8619)
- [x] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [x] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

### CODE REVIEW

**Comment by slkasper** [comment]
@cla-bot check

**Comment by Shinnnyshinshin** [comment]
Hi @slkasper thank you so much for this contribution.  The issue you surfaced in #8619 is definitely real, but maybe addressed with a slightly different approach. Could I have a look today and reply to this thread?

**Comment by Shinnnyshinshin** [comment]
Hi @slkasper thank you again for this contribution. I was able to have a deeper look at the PR and underlying issue, and it appears to be more complex than the fix that has been proposed. [Here is a Draft PR that attempted to do a more precise fix](https://github.com/great-expectations/great_expectations/pull/8925). We are currently looking into the issue as a team, and are in the process of prioritizing the work so that you and other users will be able to use this feature as intended. 

Thank you again, and hope to hear from you again soon.

**Comment by slkasper** [comment]
thank you!

**Pull request closed without merging**
