### PR TITLE
[MAINTENANCE] Fix a typo in documentation.

### PR DESCRIPTION
**Pull request by vovavili**
- [X] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]

Just a small typo fix, nothing else.

### CODE REVIEW

**Comment by vovavili** [comment]
@cla-bot check

**Comment by vovavili** [comment]
`@cla-bot check`

**Comment by vovavili** [comment]
@cla-bot check

**Comment by klavavej** [comment]
Thanks for this contribution! The PR is failing tests because of auth issues so I'm cherry picking the commit to https://github.com/great-expectations/great_expectations/pull/10681 - thanks again!

**Pull request closed without merging**
