### PR TITLE
[BUGFIX] expect_day_count_to_be_close_to_equivalent_week_day_mean

### PR DESCRIPTION
**Pull request by HadasManor**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], or [CONTRIB]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
- Fixed bug in `expect_day_count_to_be_close_to_equivalent_week_day_mean`
- Deleted old expectation that was replaced by `expect_day_count_to_be_close_to_equivalent_week_day_mean` (same expectation but better name and with fixed bugs)

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

### CODE REVIEW

**Comment by kenwade4** [comment]
Hello @HadasManor can you pull in the latest changes from develop and resolve your merge conflicts. Can you also restore the deleted file? Thanks.

**Comment by HadasManor** [comment]
Hi @kenwade4 , I also wrote you in slack about this, I did pull the latest changes and there are still conflicts so I am not sure what is happening (also the `Resolve conflicts` button here is greyed out so I cannot even see them).

Regarding the deleted file- as I wrote in the PR description, this is an old expectation that has changed names (to the other file here), and should not have stayed. It is the same, except the deleted file is not updated and contains bugs. For the benefit of our users, it needs to be deleted

**Comment by kenwade4** [comment]
@HadasManor the button is greyed out when the conflict cannot be resolved automatically

```
% git pull

% git merge origin/develop

% vim contrib/experimental/great_expectations_experimental/expectations/expect_day_count_to_be_close_to_equivalent_week_day_mean.py
...
        # get counts for dates
        query = (
<<<<<<< HEAD
            sa.select([sa.func.Date(column), sa.func.count()])
            .group_by(sa.func.Date(column))
            .select_from(selectable)
            .order_by(sa.func.Date(column).desc())
            .limit(METRIC_SAMPLE_LIMIT)
=======
            sa.select(sa.func.Date(column), sa.func.count())
            .group_by(sa.func.Date(column))
            .select_from(selectable)
            .order_by(sa.func.Date(column).desc())
            .limit(30)
>>>>>>> origin/develop
        )
        results = sqlalchemy_engine.execute(query).fetchall()
```

I'd guess to keep the chunk that uses `.limit(METRIC_SAMPLE_LIMIT)`, delete the other chunk, delete the <<<<< >>>>>> ===== lines

```
% git add contrib/experimental/great_expectations_experimental/expectations/expect_day_count_to_be_close_to_equivalent_week_day_mean.py

% git rm contrib/experimental/great_expectations_experimental/expectations/expect_yesterday_count_compared_to_avg_equivalent_days_of_week.py

% git commit
``` 

You will also need to update the `renamed` dict here https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/expectations/registry.py#L388-L391 ... put the old Expectation name as the key and the new one as the value.

**Comment by HadasManor** [comment]
I obviously did that, but I don't get the same thing as what you're seeing, that's why I was asking for help :) I keep getting "Already up to date"
image

**Review by kenwade4 — APPROVED** [review]

**Pull request merged**
