### PR TITLE
[DOCS] Add CTA announcement bar for public preview to docs

### PR DESCRIPTION
**Pull request by Rachel-Reverie**
## Description
- Adds an announcement bar with a CTA for public preview

## Definition of done
- [X] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Appropriate tests and docs have been updated

### CODE REVIEW

**Comment by kwcanuck** [comment]
@kyleaton - dumb question - where does the new announcement bar appear?

**Comment by kyleaton** [comment]
> @kyleaton - dumb question - where does the new announcement bar appear?

Great question @kwcanuck. Everywhere.

**Comment by kwcanuck** [comment]
@kyleaton - thanks for clarifying. I don't see the announcement bar in the preview build. I'm not sure how I can miss it if it's everywhere...

**Comment by kyleaton** [comment]
@kwcanuck it looks like the preview deploy was skipped? Could you pull down the branch and preview it that way?

**Review by kwcanuck — APPROVED** [review]
Unable to review changes.

**Pull request merged**
