### PR TITLE
[BUGFIX] Fix format of UnexpectedRowsExpectation observed_value to be int

### PR DESCRIPTION
**Pull request by tyler-hoffman**
Previously this was a string, but we should keep this consistent with other expectations.

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [ ] Code is linted - run `invoke lint` (uses `ruff format` + `ruff check`)
- [ ] Appropriate tests and docs have been updated

For more information about contributing, visit our [community resources](https://docs.greatexpectations.io/docs/core/introduction/community_resources#contribute-code-or-documentation).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

### CODE REVIEW

**Review by cdkini — APPROVED** [review]

**Review by NathanFarmer — CHANGES_REQUESTED** [review]
I'm not sure I agree with this change. There are lots of observed values that are strings in our codebase. Where did the requirements for this come from?

**Comment by NathanFarmer** [comment]
[Here is a great example](https://github.com/great-expectations/great_expectations/blob/49b124accbff7499416f06cfff8f26b6fe961446/great_expectations/expectations/expectation.py#L979). One of the most common observed values we have is a string.

**Comment by tyler-hoffman** [comment]
> . Where did the requirements for this come from?
@NathanFarmer 
That's fair pushback. It's from https://greatexpectations.atlassian.net/browse/CORE-632. I agree with the ticket because it favors actual values over human readable descriptions, but I'll open a thread in slack for more visibility.

**Review by NathanFarmer — APPROVED** [review]
I dug deeper and it looks like you are right. The line I linked only gets added to renderers.

**Pull request merged**
