### PR TITLE
[MAINTENANCE] Update build_in_memory_runtime_context to accept which datasources to include

### PR DESCRIPTION
**Pull request by kenwade4**
- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [ ] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], , [CONTRIB]
- [ ] Code is linted

    ```
    black .

    ruff . --fix
    ```
- [ ] Appropriate tests and docs have been updated

For more details, see our [Contribution Checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist), [Coding style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style), and [Documentation style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/docs_style).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

### CODE REVIEW

**Comment by Shinnnyshinshin** [comment]
I like the change, but it looks like there are some typing issues that will need to be resolved.

**Review by Shinnnyshinshin — COMMENTED** [review]
`pandas` is a default requirement for GX, while `spark` is optional.  Would it make more sense to only have the `include_spark` flag while keeping the `pandas` Datasource as default? Would like to hear the rest of the teams' opinion as well.

**Comment by kenwade4** [comment]
I didn't want to break compatibility with how `build_in_memory_runtime_context` was being used already (which is to make spark and pandas). It is only used in some test files and in the `build_*_validator_with_data` functions of `great_expectations/self_check/util.py` (which themselves are only used in test files).

Just because pandas is installed to the venv by default, it doesn't mean that a pandas in memory context is needed (especially for spark-only tests).

**Comment by Shinnnyshinshin** [comment]
That's a good point @kenwade4 happy to approve ✅

**Review by Shinnnyshinshin — APPROVED** [review]

**Pull request merged**
