### PR TITLE
[BUGFIX] fix issue-7954

### PR DESCRIPTION
**Pull request by jkingdon-ms**
- [x] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues/7954)
- [x] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [x] Code is linted

    ```
    black .

    ruff . --fix
    ```

For more details, see our [Contribution Checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist), [Coding style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style), and [Documentation style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/docs_style).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

### CODE REVIEW

**Comment by jkingdon-ms** [comment]
@cla-bot check

**Comment by jkingdon-ms** [comment]
@cla-bot check

**Comment by jkingdon-ms** [comment]
@cla-bot check

**Comment by jkingdon-ms** [comment]
@cla-bot check

**Comment by jkingdon-ms** [comment]
please contact @sean-tate if there are any updates on this. thank you!

**Comment by Shinnnyshinshin** [comment]
Hi @sean-tate and @jkingdon-ms, it does look like the user associated with `jameskingdon@.microsoft.com` is still missing the CLA.  Is the `.microsoft.com` address the on associated with your github account?

**Comment by jkingdon-ms** [comment]
Hey @Shinnnyshinshin yes that email address is associated with my github account. I've submitted the form with `jameskingdon@microsoft.com` as the email address twice but no luck yet.

**Comment by jkingdon-ms** [comment]
@cla-bot check

**Comment by jkingdon-ms** [comment]
Hey @Shinnnyshinshin I've just submitted the CLA again via [Software Grant and Corporate Contributor License Agreement v1.0](https://docs.google.com/forms/d/e/1FAIpQLSf3RZ_ZRWOdymT8OnTxRh5FeIadfANLWUrhaSHadg_E20zBAQ/viewform?usp=sf_link) with my email 'jameskingdon@microsoft.com' and commented `@cla-bot check`. Still, I am seeing the `verification/cla-signed` check is failing. What is missing here? Thanks

**Comment by Shinnnyshinshin** [comment]
Hi @jkingdon-ms It looks like the bot is saying `jameskingdon@.microsoft.com` is the one that is missing the CLA. is there a chance an email address was entered with an extra `.` before `microsoft`? Either in the github account config or the original CLA submission

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by Shinnnyshinshin** [comment]
We were able to take care of the CLA on our end. @jkingdon-ms Thank you very much for your contribution :)

**Review by Shinnnyshinshin — APPROVED** [review]
LGTM

**Comment by jkingdon-ms** [comment]
Thanks everyone!

**Pull request merged**
