### PR TITLE
[FEATURE] Allow using EmailAction with email servers that require no authentication (fixes #9379)

### LINKED ISSUE #9379: Cannot send Email via EmailAction, when (internal) Email server does not need authentication
**Describe the bug**
One is not able to send an Email via an internal server that does not require authentication (see below).

I would be willing do create a PR to fix this, if it is fine, that GX supports sending such emails.

**To Reproduce**
I am using the EmailAction class to send a summary validation result to an email address

```
from great_expectations.checkpoint import EmailAction
action = EmailAction(
            data_context=None,
            renderer={
                "module_name": "great_expectations.render.renderer.email_renderer",
                "class_name": "EmailRenderer",
            },
            smtp_address=smtp_address,
            smtp_port=smtp_port,
            sender_login=sender_login,
            sender_password=sender_password,
            receiver_emails=",".join(recipients),
            sender_alias=sender_alias,
            use_ssl=security_protocol.lower() == "ssl",
            use_tls=security_protocol.lower() == "tls",
            notify_on=self._notify_on,
            notify_with=None,
        )
```
When I try to run the action via `action.run(...)`
I get 

> ┌───────────────────── Traceback (most recent call last) ─────────────────────┐
> │ C:\XXXXX\scratches\scra │
> │ tch_5.py:19 in <module>                                                     │
> │                                                                             │
> │   16 │   "recipients": ["XXXXX"]                         │
> │   17 }                                                                      │
> │   18                                                                        │
> │ > 19 notifier = EmailNotifier(**email_notifier)                             │
> │   20                                                                        │
> │   21 summary_validation_result = ExpectationSuiteValidationResult(          │
> │   22 │   success=True,                                                      │
> │                                                                             │
> │ XXXXX\venv\lib\site-packages\kedro_expectat │
> │ ions\notification.py:85 in __init__                                         │
> │                                                                             │
> │    82 │   │   │   notify_on=notify_on,                                      │
> │    83 │   │   │   subject=subject,                                          │
> │    84 │   │   )                                                             │
> │ >  85 │   │   self._action = EmailAction(                                   │
> │    86 │   │   │   data_context=None,                                        │
> │    87 │   │   │   renderer={                                                │
> │    88 │   │   │   │   "module_name": "great_expectations.render.renderer.em │
> │                                                                             │
> │ XXXXXXX\venv\lib\site-packages\great_expectat │
> │ ions\checkpoint\actions.py:760 in __init__                                  │
> │                                                                             │
> │    757 │   │   self.use_ssl = use_ssl                                       │
> │    758 │   │   assert smtp_address, "No SMTP server address found in action │
> │    759 │   │   assert smtp_port, "No SMTP server port found in action confi │
> │ >  760 │   │   assert sender_login, "No login found for sending the email i │
> │    761 │   │   assert (                                                     │
> │    762 │   │   │   sender_password                                          │
> │    763 │   │   ), "No password found for sending the email in action config │
> └─────────────────────────────────────────────────────────────────────────────┘
> AssertionError: No login found for sending the email in action config.
> 

However I must not provide a login as the server does not require one (it is an internal server and only allow specific recipients).
When I provide None or empty strings as login and password, it won't work, as the great expectation utils methos `send_email` always tries to perform a login with the provided login/password, which will fail.

**Expected behavior**
Should be able to send an email to an internal email server that does not require authentication, by not defining `sender_login` and `sender_password` (or define it as None).

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.18.8
 - Data Source: None
 - Cloud environment: None

**Additional context**

### PR DESCRIPTION
**Pull request by MarcelBeining**
This PR allows the use of EmailAction with (e.g. internal) email servers that do not require authentication, fixing issue (#9379)

- [x] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [x] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [x] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [x] Appropriate tests and docs have been updated

### CODE REVIEW

**Comment by MarcelBeining** [comment]
@cla-bot check

**Review by TrangPham — APPROVED** [review]
Thanks for this bugfix!

**Comment by MarcelBeining** [comment]
When is this PR finally in Release? It's 2,5 months since then

**Comment by MarcelBeining** [comment]
@anthonyburdi  ?

**Pull request merged**
