### PR TITLE
[FEATURE] Added AssumeRole Feature

### PR DESCRIPTION
**Pull request by Reactor11**
I'm hosting my GX components(Validations, Data Docs etc) in s3 using TupleS3StoreBackend in different aws account (Say PROD), Now I want to use the same GX context in different aws account (Say PCI), Since using IAM role is the recommended way instead of using IAM user.

We should be able to give which role to assume while writing in [boto_options](https://docs.greatexpectations.io/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_amazon_s3/#3-update-your-configuration-file-to-include-a-new-store-for-expectations-on-s3) and it should automatically assume the role and write to s3.

Alternatives that I have consider is, I've a separate flow that will assume role and set the credentials in env, post which i'll load GX context

Example config right now -

```
checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: bucket
      prefix: checkpoint/
      boto3_options:
        aws_access_key_id: ${DQ_SESSION_ID}
        aws_secret_access_key: ${DQ_SESSION_KEY}
        aws_session_token: ${DQ_SESSION_TOKEN}
```

Example config expected:
```
checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: bucket
      prefix: checkpoint/
      boto3_options:
        aws_assume_role_arn: ${role-arn}
```

Changes proposed in this pull request:
- It will pick assume role arn from boto3_options, If it is provided by the user, it will assume that role, get the credentials and set them in boto3_options with keys as aws_access_key_id, aws_secret_access_key, aws_session_token.
- User can provide region_name, assume_role_duration which are required during assuming that role.

Issue Link - https://github.com/great-expectations/great_expectations/issues/7546

### CODE REVIEW

**Comment by kenwade4** [comment]
Hi @Reactor11 thanks for this PR, can you please [lint your code](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style/#linting), commit the changes, pull in latest from the develop branch and push up?

```
black great_expectations/data_context/store/tuple_store_backend.py
```

As a first-time contributor, you will also need to sign one of the contributor license agreements. I'm guessing the [one for individuals](https://docs.google.com/forms/d/e/1FAIpQLSdA-aWKQ15yBzp8wKcFPpuxIyGwohGU1Hx-6Pa4hfaEbbb3fg/viewform) will be fine for you.

Can you edit the title of the PR to begin with one of these: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], or [CONTRIB]

And finally, can you update the actual content of the PR? You can click the horizontal 3 dots and click "Edit"

- At minimum, add a bullet point to the `Changes proposed in this pull request` section
- You can replace the template paragraph of PR instructions above that section with a sentence/paragraph describing why the change is added and linking to an existing issue on github.

**Comment by tb102122** [comment]
@Reactor11 can you lint and resubmit the code I would need the feature as well.

**Comment by Reactor11** [comment]
@cla-bot check

**Comment by Reactor11** [comment]
@kenwade4 I've made the suggested changes, could you please review now?

**Review by kenwade4 — APPROVED** [review]

**Comment by Reactor11** [comment]
hey @kenwade4 thanks for the review, I was wondering what are the next steps for this PR?

**Comment by kenwade4** [comment]
@Reactor11 did you sign one of the CLA forms before you did `@cla-bot check`? If so I'll check with someone internally as to why the bot is not passing you. After that it just needs to wait it's turn to get merged.

**Comment by kyleaton** [comment]
@cla-bot check

**Pull request merged**
