### PR TITLE
[BUGFIX] SQLAlchemy version 1.3.24 compatibility in map metric provider

### PR DESCRIPTION
**Pull request by shpolina**
Related to #3499 

Fix code in map metric provider that is incompatible with SQLAlchemy version 1.3.24.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by talagluck — APPROVED** [review]
LGTM - thanks for this, @shpolina!

**Comment by talagluck** [comment]
@shpolina - it looks like tests are failing. Would you mind taking a look and seeing if you're able to fix? Let me know if you need any help here. Thanks!

**Comment by shpolina** [comment]
@talagluck I don't think these failures are related to my change, I am seeing similar failures on other PRs.

**Comment by talagluck** [comment]
Yes, I believe you are right, @shpolina - sorry for the red herring, and thanks again for the fix!

**Comment by talagluck** [comment]
Resolves #3557

**Pull request merged**
