### PR TITLE
[BUGFIX] remove connection log for v1

### PR DESCRIPTION
**Pull request by rreinoldsc**
Accompanying PR for one merged into 0.18.x:

https://github.com/great-expectations/great_expectations/pull/9136

- [ ] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [x] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [x] Code is linted - run `invoke lint` (uses `black` + `ruff`)
- [x] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

### CODE REVIEW

**Review by Shinnnyshinshin — APPROVED** [review]
Thank you for the quick patch @rreinold

**Comment by TrangPham** [comment]
@rreinoldsc Is there a reason this has not been merged yet?

**Comment by rreinoldsc** [comment]
ensuring this security issue makes it into both `0.18.x` and `develop`

**Comment by rreinoldsc** [comment]
> @rreinoldsc Is there a reason this has not been merged yet?

No reason. This was prioritized for patch on `0.18.x` branch, and just now coming back to ensure it goes into v1.0 `develop` branch

**Pull request merged**
