### PR TITLE
[DOCS] Remove CE templates & examples

### PR DESCRIPTION
**Pull request by austiezr**
Removes all deprecated Custom Expectation templates, example files, and relevant tests

- [x] Description of PR changes above includes a link to [an existing GitHub issue](https://github.com/great-expectations/great_expectations/issues)
- [x] PR title is prefixed with one of: [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], [CONTRIB]
- [x] Code is linted - run `invoke lint` (uses `ruff format` + `ruff check`)
- [x] Appropriate tests and docs have been updated

For more information about contributing, see [Contribute](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

After you submit your PR, keep the page open and **monitor the statuses of the various checks made by our continuous integration process at the bottom of the page. Please fix any issues that come up** and [reach out on Slack](https://greatexpectations.io/slack) if you need help. Thanks for contributing!

### CODE REVIEW

**Review by Rachel-Reverie — APPROVED** [review]
LGTM.  The `.md` files that are supported by these examples have already been removed, so as long as they aren't causing failures in `test_script_runner.py` I don't think we need them any more.

**Comment by planck-length** [comment]
Hello, just to check does this has something with error 404 return when I click on this [link](https://github.com/great-expectations/great_expectations/blob/develop/examples/expectations/query_expectation_template.py) to get me to 
`query_expectation_template.py.`?

**Comment by maltequast** [comment]
Hi, why did you delete the ce template? It is still referenced on your [documentation page](https://docs.greatexpectations.io/docs/oss/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations).

How do I create my own expectations by now? Is there another workflow I am not aware of?

**Comment by ckarrasalithya** [comment]
I have the same issue as @planck-length @maltequast: I wanted to create custom expectations but was unable to follow the documentation because it referenced the examples that were deleted as part of this PR. I also could not find any documentation in the 1.0 docs about a new way to write expectations.

The PR description mentions that the examples are deprecated, so what is the correct way to write custom expectations going forward?

Note that I was able to write a custom expectations by retrieving the versions of the examples just before this PR was merged in the Git history, and they work fine, but before going too far in creating custom expectations, I would like to make sure I won't have to do a major rewrite of these expectations once v1.0 is released.

**Pull request merged**
