### PR TITLE
[MAINTENANCE] Return empty set instead of None

### PR DESCRIPTION
**Pull request by anthonyburdi**
Changes proposed in this pull request:
- In `_get_reader_options_include` modify the return type to set only and instead of returning None return an empty set

### CODE REVIEW

**Review by Kilo59 — APPROVED** [review]

**Review by billdirks — APPROVED** [review]
LGTM!

**Review by Shinnnyshinshin — APPROVED** [review]
I know this PR already has the approvals it needs, but wanted to review for my education :) Thank you for this @anthonyburdi

**Review by Shinnnyshinshin — APPROVED** [review]
I know this PR already has the approvals it needs, but wanted to review for my education :) Thank you for this @anthonyburdi

**Review by Shinnnyshinshin — APPROVED** [review]
I know this PR already has the approvals it needs, but wanted to review for my education :) Thank you for this @anthonyburdi

**Review by Shinnnyshinshin — APPROVED** [review]
I know this PR already has the approvals it needs, but wanted to review for my education :) Thank you for this @anthonyburdi

**Pull request merged**
